server:
  port: ${server.port}

spring:
  application:
    name: ${name}
    description: ${description}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
  batch:
    jdbc:
      initialize-schema: always

batch:
  file_path: "file:"
  strict_mode: true
  shutdown_after_execute: false

management:
  server:
    port: ${management.port}
  metrics:
    export:
      prometheus:
        enabled: false
    tags:
      application: wb-list-manager
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

client:
  cds:
    url: http://127.0.0.1:8023/v1/storage
    timeout: 5000
